name: .NET

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      test-directory: test-reports

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --logger trx -r ./test-reports --collect:"XPlat Code Coverage" --settings "./coverlet.runsettings"

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: ${{env.test-directory}}/*.trx
          reporter: dotnet-trx

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.10
        with:
          reports: ${{env.test-directory}}/*/coverage.cobertura.xml
          reporttypes: "lcov;HtmlInline;Cobertura"
          targetdir: "coveragereport"
          tag: "${{ github.run_number }}_${{ github.run_id }}"

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport # Artifact name
          path: coveragereport # Directory containing files to upload

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{env.test-directory}}/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"
